// automatically generated by the FlatBuffers compiler, do not modify

export { Color } from './my-game/sample/color.js';
export { Equipment, unionToEquipment, unionListToEquipment } from './my-game/sample/equipment.js';
export { Monster } from './my-game/sample/monster.js';
export { Vec3 } from './my-game/sample/vec3.js';
export { Weapon } from './my-game/sample/weapon.js';
